repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies:
          - fastapi
          - pydantic
          - pydantic-settings
          - sqlalchemy[asyncio]
        args: [--ignore-missing-imports]

  - repo: local
    hooks:
      - id: vulture
        name: vulture
        entry: vulture
        args: [src/, vulture_whitelist.py, --min-confidence=80]
        language: system
        types: [python]
        pass_filenames: false
