"""add spec_draft_id to project

Revision ID: 0053220bed75
Revises: 937313d4523a
Create Date: 2026-05-06 22:52:13.183593

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0053220bed75"
down_revision: str | None = "937313d4523a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("spec_draft_id", sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(
        None, "projects", "spec_drafts", ["spec_draft_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.drop_column("projects", "spec_draft_id")
    # ### end Alembic commands ###
