"""add indexes constraints and soft delete

Revision ID: 02b84f2b2a2d
Revises: 001
Create Date: 2026-04-25 14:02:56.264593

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "02b84f2b2a2d"
down_revision: str | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
