"""add multi-spec and workspace team association

Revision ID: d5b1a0f1f999
Revises: 35d128585feb
Create Date: 2026-04-29 14:55:52.434914

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5b1a0f1f999"
down_revision: str | None = "35d128585feb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create specs table
    op.create_table(
        "specs",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("workspace_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("spec_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status", sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="specstatus"), nullable=False
        ),
        sa.Column("created_by_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "name", "version", name="uq_specs_workspace_name_version"
        ),
    )
    op.create_index("ix_specs_created_by_id", "specs", ["created_by_id"], unique=False)
    op.create_index("ix_specs_workspace_id", "specs", ["workspace_id"], unique=False)

    # Create workspace_teams association table
    op.create_table(
        "workspace_teams",
        sa.Column("workspace_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("team_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("workspace_id", "team_id"),
    )
    op.create_index("ix_workspace_teams_team_id", "workspace_teams", ["team_id"], unique=False)
    op.create_index(
        "ix_workspace_teams_workspace_id", "workspace_teams", ["workspace_id"], unique=False
    )

    # Step 1: Add workspace_id as nullable first
    op.add_column("spec_drafts", sa.Column("workspace_id", sa.UUID(as_uuid=False), nullable=True))
    op.add_column("spec_drafts", sa.Column("source_spec_id", sa.UUID(as_uuid=False), nullable=True))

    # Step 2: Migrate existing drafts - assign to first workspace in the draft's tenant
    op.execute("""
        UPDATE spec_drafts
        SET workspace_id = (
            SELECT w.id
            FROM workspaces w
            WHERE w.tenant_id = spec_drafts.tenant_id
            ORDER BY w.created_at ASC
            LIMIT 1
        )
        WHERE workspace_id IS NULL
    """)

    # Step 3: Delete orphaned drafts (those in tenants with no workspaces)
    op.execute("""
        DELETE FROM spec_drafts WHERE workspace_id IS NULL
    """)

    # Step 4: Make workspace_id NOT NULL
    op.alter_column("spec_drafts", "workspace_id", nullable=False)

    # Step 5: Update constraints and indexes
    op.drop_index(op.f("ix_spec_drafts_tenant_id"), table_name="spec_drafts")
    op.drop_constraint(op.f("uq_spec_drafts_tenant_user"), "spec_drafts", type_="unique")
    op.create_index("ix_spec_drafts_user_id", "spec_drafts", ["user_id"], unique=False)
    op.create_index("ix_spec_drafts_workspace_id", "spec_drafts", ["workspace_id"], unique=False)
    op.create_unique_constraint(
        "uq_spec_drafts_workspace_user_name", "spec_drafts", ["workspace_id", "user_id", "name"]
    )
    op.drop_constraint(op.f("spec_drafts_tenant_id_fkey"), "spec_drafts", type_="foreignkey")
    op.create_foreign_key(
        None, "spec_drafts", "specs", ["source_spec_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "spec_drafts", "workspaces", ["workspace_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("spec_drafts", "tenant_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "spec_drafts", sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "spec_drafts", type_="foreignkey")
    op.drop_constraint(None, "spec_drafts", type_="foreignkey")
    op.create_foreign_key(
        op.f("spec_drafts_tenant_id_fkey"),
        "spec_drafts",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_spec_drafts_workspace_user_name", "spec_drafts", type_="unique")
    op.drop_index("ix_spec_drafts_workspace_id", table_name="spec_drafts")
    op.drop_index("ix_spec_drafts_user_id", table_name="spec_drafts")
    op.create_unique_constraint(
        op.f("uq_spec_drafts_tenant_user"),
        "spec_drafts",
        ["tenant_id", "user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("ix_spec_drafts_tenant_id"), "spec_drafts", ["tenant_id"], unique=False)
    op.drop_column("spec_drafts", "source_spec_id")
    op.drop_column("spec_drafts", "workspace_id")
    op.drop_index("ix_workspace_teams_workspace_id", table_name="workspace_teams")
    op.drop_index("ix_workspace_teams_team_id", table_name="workspace_teams")
    op.drop_table("workspace_teams")
    op.drop_index("ix_specs_workspace_id", table_name="specs")
    op.drop_index("ix_specs_created_by_id", table_name="specs")
    op.drop_table("specs")
    # ### end Alembic commands ###
