---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart metaseed-hub
  ansible.builtin.systemd:
    name: metaseed-hub
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
